<?php

namespace app\models;

use app\models\Category;
use Yii;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property int $cost
 * @property string $title
 * @property string $detail
 * @property string $gender
 * @property string|null $brand
 * @property string|null $category
 * @property int|null $hidden
 * @property int|null $new
 * @property int|null $sale
 *
 * @property OrderItem[] $orderItems
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cost', 'title', 'gender'], 'required'],
            [['cost', 'hidden', 'new', 'sale'], 'integer'],
            [['title', 'detail', 'gender', 'brand_id', 'category_id'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cost' => 'Стоимость',
            'title' => 'Описание',
            'detail' =>'Подробное описание',
            'gender' => 'Пол',
            'brand_id' => 'Бренд',
            'category_id' => 'Категория',
            'hidden' => 'Скрыт',
            'new' => 'Новинка',
            'sale' => 'Распродажа',
        ];
    }

    /**
     * Gets query for [[OrderItems]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOrderItems()
    {
        return $this->hasMany(OrderItem::className(), ['product_id' => 'id']);
    }

    public function saveImage($filename) // УДАЛИТЬ? дублирует функционал ImageUpload
    {
        $this->image = $filename;
        return $this->save(false);
    }

    public function deleteImage() // УДАЛИТЬ? дублирует функционал ImageUpload
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }
    public function beforeDelete() // УДАЛИТЬ? дублирует функционал ImageUpload
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function showImage() // УДАЛИТЬ? дублирует функционал ImageUpload
    {
        return ($this->image) ? '/uploads/' . $this->image : '/images/no-image.png';
    }

    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }

    public function saveCategory($category_id) // функция сохранения категории в товаре
    {
        $category = Category::findOne($category_id); // передаём найденную категорию в переменную
        if ($category != null) // если оне не NULL
        {
            $this->link('category', $category); // делаем на неё ссылку
            return true; // и возвращаем TRUE
        }
    }

    public function getBrand()
    {
        return $this->hasOne(Brand::class, ['id' => 'brand_id']);
    }

    public function saveBrand($brand_id) // функция сохранения бренда в товаре
    {
        $brand = Brand::findOne($brand_id); // передаём найденный бренд в переменную
        if ($brand != null) // если оне не NULL
        {
            $this->link('brand', $brand); // делаем на неё ссылку
            return true; // и возвращаем TRUE
        }
    }

    public static function brandCount($id) // счётчик товаров определённого бренда
    {
        $count = Product::find()
            ->where(['brand_id' => $id])
            ->count();
        echo $count;
    }
}
